[package]
name = "control-deamon"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
rcon = { version = "0.6.0", features = ["rt-tokio"]}
tokio = { version = "1.48.0", features = ["rt-multi-thread", "time"] }

